### ISSUE TITLE
Feature request - /rankup based on economy

### ISSUE THREAD

**Issue by ProsperCraft** [tacticalsk8er/AutoRank#1]
would love to see the time requirement able to disable and have an option to /rankup based on players ingame economy balance.

**Comment by tacticalsk8er** [comment]
I am working on another plugin that will handle this feature and many more tests. This plugin will be only for ranking up based on playtime. If you want to follow this repo: https://github.com/tacticalsk8er/Rewards. I will be adding a README soon.
